version: 2.1

orbs:
  rust: circleci/rust@1.6.2
workflows:
  test:
    jobs:
      - Test
jobs:
  Test:
    docker:
      - image: cimg/rust:1.86.0
    steps:
      - checkout
      - run: sudo apt update && sudo apt-get install -y build-essential pkg-config cmake libopus0
      - rust/test
